### ISSUE TITLE
examples中的tars-spring-boot-server运行时报错

### ISSUE THREAD

**Issue by deepzliu** [TarsCloud/TarsJava#54]
各位大佬，tars-spring-boot-server运行时报错。看起来像是按tars协议处理了，应该是走非tars协议才对。求帮忙看下，谢谢！

代码：
`package com.qq.tars.quickstart.server;
import com.qq.tars.server.core.ContextManager;
import com.qq.tars.spring.annotation.EnableTarsServer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import com.qq.tars.spring.annotation.TarsHttpService;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@EnableTarsServer
@TarsHttpService("HttpObj")
@RestController
public class QuickStartApplication {
    public static void main(String[] args) {
        SpringApplication.run(QuickStartApplication.class, args);
    }   
    @RequestMapping(path = "/test")
    public String test() {
        return "hello world";
    }   
}`

启动时有报这个错，但能正常启动，端口监听也正常。
`Exception in thread "ServantThreadPool-exec-null-1" java.lang.NoClassDefFoundError: com/qq/tars/server/core/ContextManager
	at com.qq.tars.server.core.TarsServantProcessor.process(TarsServantProcessor.java:180)
	at com.qq.tars.net.core.nio.WorkThread.run(WorkThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.qq.tars.server.core.ContextManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 5 more
`

收到http请求后，服务报的错如下。看起来像是按tars协议处理了，应该是走非tars协议才对。
`com.qq.tars.net.protocol.ProtocolException: the length header of the package must be between 0~10M bytes. data length:504f5350
	at com.qq.tars.rpc.protocol.tars.TarsCodec.decodeRequest(TarsCodec.java:254)
	at com.qq.tars.net.core.nio.TCPSession.readRequest(TCPSession.java:119)
	at com.qq.tars.net.core.nio.TCPSession.read(TCPSession.java:97)
	at com.qq.tars.net.core.nio.TCPAcceptor.handleReadEvent(TCPAcceptor.java:77)
	at com.qq.tars.net.core.nio.Reactor.dispatchEvent(Reactor.java:183)
	at com.qq.tars.net.core.nio.Reactor.run(Reactor.java:104)
`

**Comment by TimmyYu** [comment]
这个需要理提供一下平台上面servant的配置。平台上HttpObj的配置类型是否你正常。再提供一下tras的版本

**Comment by DonghuaLau** [comment]
![微信图片_20191217081506](https://user-images.githubusercontent.com/3375613/70953759-69815e00-20a5-11ea-8aef-bfaa1c424453.png)
![微信图片_20191217081513](https://user-images.githubusercontent.com/3375613/70953764-6e461200-20a5-11ea-98dd-7a0c45893a25.png)
![democgi-conf](https://user-images.githubusercontent.com/3375613/70953771-73a35c80-20a5-11ea-8894-97221cbcab2e.jpg)

**Comment by TimmyYu** [comment]
依赖需要都使用1.7.0。里面的日志库两个版本中并不通用。所以依赖需要使用新版本的依赖库才可以

**Comment by duanyongyao** [comment]
遇到同样问题
tars框架版本是1.0.1
tars-spring-boot-starter的版本是1.7.1
